include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-tailscale
PKG_VERSION:=1.0
PKG_RELEASE:=1

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Community

LUCI_TITLE:=LuCI support for Tailscale Killswitch
LUCI_DEPENDS:=+tailscale

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
